---
title: "AE Competition"
output: html_notebook
---

Read in datasets
```{r}
setwd("D:/School Stuff/40 .220 The Analytics Edge/Competition/Code")
dataset1 <- read.csv("../Data/train_dataset01.csv")
dataset2 <- read.csv("../Data/train_dataset02.csv")
dataset3 <- read.csv("../Data/test_dataset.csv")
sample <- read.csv("../Data/sample_submission.csv")

```

F1 Calculator based on TP, FP and FN
```{r}
F1calc <- function(TP,FP,FN){
  p = TP/ (TP+FP)
  r = TP/ (TP+FN)
  return((2*p*r)/(p+r))
}

```


```{r}
str(dataset1)
str(dataset2)

```

Full dataset glm (all var)

```{r}
library(caTools)
set.seed(2e4)
split <- sample.split(dataset2$ATT_FLAG, SplitRatio = 0.7)
train <- subset(dataset2, split == TRUE)
validation <- subset(dataset2, split == FALSE)

fullglmsplit <- sample.split(train$ATT_FLAG, SplitRatio = 0.7)
fullglmtrain <- subset(train, fullglmsplit == TRUE)
fullglmtest <- subset(train, fullglmsplit == FALSE)
```

Randforest
```{r}
library(randomForest)
set.seed(2e4)
forest_fulldata <- randomForest(data = fullglmtrain, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)

pred.forest_fulldata <- predict(forest_fulldata)
FDRF <- table(pred.forest_fulldata, fullglmtrain$ATT_FLAG)

print("On Training Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = fullglmtest)
FDRF <- table(pred.forest_fulldata, fullglmtest$ATT_FLAG)

print("On Test Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = validation)
FDRF <- table(pred.forest_fulldata, validation$ATT_FLAG)
print("On Validation Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = dataset1)
FDRF <- table(pred.forest_fulldata, dataset1$ATT_FLAG)

print("On Dataset 1")
FDRF
```


Checking RF
```{r}
vu <- varUsed(forest_fulldata, count= TRUE)                      #freq of variables used in the random forest
vusorted <- sort(vu, decreasing = FALSE, index.return = TRUE) #sorts the fq
dotchart(vusorted$x, names(forest_fulldata$forest$xlevels[vusorted$ix])) #draws a cleveland dot plot

varImpPlot(forest_fulldata) #looking at impurity metric > want to find average reduction in impurity
importance(forest_fulldata) #see which variables are the most impt (higher = more impt)
```

## LASSO ##
Define Model
```{r}
library(glmnet)
lassoX <- model.matrix(ATT_FLAG~LEVEL_T1+LEVEL_T4+LEVEL_T7+PRESSURE_J415+PRESSURE_J269+PRESSURE_J14+PRESSURE_J317+FLOW_PU1+FLOW_PU6+FLOW_PU7+STATUS_PU6+STATUS_PU7, fullglmtrain)
lassoY <- fullglmtrain$ATT_FLAG
grid<-10^seq(10,-2, length=100)


modellasso <- glmnet(lassoX,lassoY,lambda=grid, family="binomial")
plot(modellasso,xvar="lambda")
```
Cross validation for lambda
```{r}
set.seed(1e4)
cvlasso <- cv.glmnet(lassoX,lassoY,lambda=grid, family="binomial")   #lambda=grid may help (default is NULL)
#cvlasso$glmnet.fit
cvlasso$lambda.min #find best lambda
#plot(cvlasso$lambda,cvlasso$cvm)
```

```{r}
newX = model.matrix(ATT_FLAG~LEVEL_T1+LEVEL_T4+LEVEL_T7+PRESSURE_J415+PRESSURE_J269+PRESSURE_J14+PRESSURE_J317+FLOW_PU1+FLOW_PU6+FLOW_PU7+STATUS_PU6+STATUS_PU7, fullglmtest)
predictlassocv <- predict(modellasso,s=cvlasso$lambda.min,newx=newX) #use the best lambda for CV
mean((predictlassocv -y[test])^2) #mean squared error
```




## CART ##
Define Model
```{r}
library(rpart)
library(rpart.plot)    
library(rattle)	      #optional	
library(RColorBrewer) #optional
```
Define Model
```{r}
cart1 <- rpart(data=fullglmtrain, ATT_FLAG~LEVEL_T1+LEVEL_T4+LEVEL_T7+PRESSURE_J415+PRESSURE_J269+PRESSURE_J14+PRESSURE_J317+FLOW_PU1+FLOW_PU6+FLOW_PU7+STATUS_PU6+STATUS_PU7, method = "class", cp=0.01)
printcp(cart1)
#print(cart1)

cart2 <- rpart(data=df1, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2, method = "class", cp=0.001)
```

Predictions
```{r}
predictcart1 <- predict(cart1, type = "class")  
CARTConMat<- table(predictcart1, fullglmtrain$ATT_FLAG)
print("On Train Dataset")
CARTConMat
F1calc(CARTConMat[4],CARTConMat[2],CARTConMat[3])

predictcart1 <- predict(cart1, newdata = fullglmtest, type = "class")  
CARTConMat<- table(predictcart1, fullglmtest$ATT_FLAG)
print("On TEST Dataset")
CARTConMat
F1calc(CARTConMat[4],CARTConMat[2],CARTConMat[3])

predictcart1 <- predict(cart1, newdata = validation, type = "class")  
CARTConMat<- table(predictcart1, validation$ATT_FLAG)
print("On Validation Dataset")
CARTConMat
F1calc(CARTConMat[4],CARTConMat[2],CARTConMat[3])

predictcart1 <- predict(cart1, newdata = dataset1, type = "class")  
CARTConMat<- table(predictcart1, dataset1$ATT_FLAG)
print("On Dataset 1")
CARTConMat

```


Run on dataset3
```{r}
predictcart1 <- predict(cart1, newdata = dataset3, type = "class") 
predictcart2 <- predict(cart2, newdata = dataset3, type = "class") 
table(predictcart1)
table(predictcart2)
```

Writing to CSV
```{r}
view <- data.frame(cart1=predictcart1,cart2=predictcart2,best=read.csv("Team17_Try1 (0.49244).csv")$ATT_FLAG)
write.csv(view,file="viewcart.csv",row.names=FALSE)

out=data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=predictcart1)
write.csv(out,file="test.csv",row.names=FALSE)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
