---
title: "AE Competition"
output: html_notebook
---

Read in datasets
```{r}
setwd("D:/School Stuff/40 .220 The Analytics Edge/Competition/Code")
bestpred <- read.csv("../Submissions/Team17_Try6 (0.76108).csv")
spedpred <- read.csv("Team17_Try6b.csv")
dataset1 <- read.csv("../Data/train_dataset01.csv")
dataset2 <- read.csv("../Data/train_dataset02.csv")
dataset3 <- read.csv("../Data/test_dataset.csv")
sample <- read.csv("../Data/sample_submission.csv")

```

F1 Calculator based on TP, FP and FN
```{r} 
F1calc <- function(TP,FP,FN){
  p = TP/ (TP+FP)
  r = TP/ (TP+FN)
  return((2*p*r)/(p+r))
}

```


## Deviation from the Norm mtd ##
Prep training data
```{r}
#remove unecessary and non numeric data
sigdata <- subset(dataset1, select=-c(DATETIME,FLOW_PU5,FLOW_PU9,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2,ATT_FLAG))

#function to get mean and sd
meansd <- function(data){
  mean = mean(data)
  sd = sqrt(var(data))
  return(c(mean,sd))
}

sigdata_mean <- rep(NA,ncol(sigdata))
sigdata_sd <- rep(NA,ncol(sigdata))

#generate mean and sd
for (i in 1:ncol(sigdata)){
  sigdata_mean[i] = meansd(sigdata[,i])[1]
  sigdata_sd[i] = meansd(sigdata[,i])[2]
}
sigdata_mean #contains the mean values of each var
sigdata_sd   #contains the sd values of each var

```

Process input data then run dataset through the "normal" model

```{r}
#filter data
tempdf <- subset(dataset3, select=-c(DATETIME,FLOW_PU5,FLOW_PU9,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2))

coeff=3
#function to get preds
normalmethod <- function(tempdf){
  normpred <- rep(NA,nrow(tempdf))
  normpredmat <- matrix(FALSE,nrow = nrow(tempdf), ncol = ncol(tempdf),byrow = TRUE)
  
  #go through every row
  for(i in 1:nrow(tempdf)){
    #not attack on default
    flag = FALSE
    #go through every column
    for(j in 1:ncol(tempdf)){
      #if > 1sd from mean then flag trigger flag
      if(abs( tempdf[i,j] - sigdata_mean[j] ) > coeff*sigdata_sd[j]){
        flag = TRUE
        normpredmat[i,j] = TRUE
      } 
    }
    normpred[i]=flag
    
  }
  return(normpred)
}

normpred <- normalmethod(tempdf)

print("Dataset2")
NDM <- table(normpred, spedpred$ATT_FLAG)
NDM
F1calc(NDM[4],NDM[2],NDM[3])
```

Writing to CSV
```{r}
getwd()
out=data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=as.factor(normpred))
write.csv(out,file="test.csv",row.names=FALSE)

```



#####################
## Moving Averages ##
One sided MA
```{r}
library(TTR)
tempdf <- dataset3
windowsize <- 4
coeff <- 2.9

MADataset <- data.frame(apply(tempdf[,2:32], 2, EMA, n=windowsize)) #Apply Moving Average
for (i in 1:windowsize-1){
  for (j in 1:31){
    #MADataset[i,j] = tempdf[i,j] #putting back values for 1-4 (because moving average removes them)
    MADataset[i,j] = MADataset[windowsize,j] #above results it high variation, so i just put all as the mean of the 1st rolling avg
  }
}
MADataset <- subset(MADataset, select=-c(FLOW_PU5,FLOW_PU9)) #Remove filtered rows

#MAPred <- normalmethod(MADataset) 
MAPred <- normalmethod(MADataset) 

print("Dataset2")
NDM <- table(MAPred, spedpred$ATT_FLAG)
NDM
F1calc(NDM[4],NDM[2],NDM[3])

#write.csv(data.frame(MA=normpred,best=bestpred$ATT_FLAG),"viewnorm.csv",row.names = FALSE)
#write.csv(data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=read.csv("viewnorm.csv")$MA),"test.csv",row.names = FALSE)
#write.csv(data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=as.factor(MAPred)),"test.csv",row.names = FALSE)

```
Type 3,5,10,15
SMA 0.6881203, 0.7159463, 0.7219003, 0.7079194
EMA 0.7068345, 0.7217647, 0.7127294, 0.7045645
WMA 0.6859875, 0.7078584, 0.722449 , 0.7135073


Centered MA
```{r}
library(forecast)
tempdf <- dataset2
windowsize <- 5

MADataset <- data.frame(apply(tempdf[,2:32], 2, ma, order=windowsize)) #Apply Moving Average
MARow <- nrow(MADataset) - floor(windowsize/2)
for (i in 1:floor(windowsize/2)){
  for (j in 1:31){
    MADataset[i,j] = MADataset[(windowsize/2)+1,j] #above results it high variation, so i just put all as the mean of the 1st rolling avg
    MADataset[MARow+i,j] = MADataset[MARow,j]
  }
}
MADataset <- subset(MADataset, select=-c(FLOW_PU5,FLOW_PU9)) #Remove filtered rows

MAPred <- normalmethod(MADataset)

print("Dataset2")
NDM <- table(MAPred, dataset2$ATT_FLAG)
NDM
F1calc(NDM[4],NDM[2],NDM[3])

#write.csv(data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=as.factor(MAPred)),"test.csv",row.names = FALSE)
```
Window size, D2 , D1
05 0.7219076 , 0.9377271
10 0.7317919 , 0.9371091
15 0.7260857 , 0.9363665



Seeing the rough ranges of acceptable values via plot on Dataset1
```{r}
for(i in 2:32){
  plot(dataset1[,i],main = colnames(dataset1[i]))
  abline(h=mean(dataset1[,i]),col="red")
}

```

Setting Acceptable Range
```{r}
#split distribution
getmeansd <- function(var){
  mean = mean(var)
  sd = sd(var)
  return(c(mean,sd))
}
getranges <- function(var){
  mean = getmeansd(var)[1]
  upper = var[var>=mean]
  lower = var[var<=mean]
  uppermeansd = getmeansd(upper)
  lowermeansd = getmeansd(lower)
  return(c(uppermeansd[1],uppermeansd[2],lowermeansd[1],lowermeansd[2]))
}

createdist <- function(DF){
  doublerange <- matrix(nrow = 4,ncol = 31,byrow = TRUE)
  for(i in 2:32){
    ranges = getranges(DF[,i])
    doublerange[1,i-1] = ranges[1]
    doublerange[2,i-1] = ranges[2]
    doublerange[3,i-1] = ranges[3]
    doublerange[4,i-1] = ranges[4]
  }
  return(doublerange)
}

doublerange <- createdist(dataset1)
doublerange
```

normpred method version 2.0
```{r}
#filter data
#tempdf <- subset(dataset2, select=-c(DATETIME,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2,ATT_FLAG))

tempdf <- subset(dataset3, select=-c(DATETIME,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2))

#threshold for sd
coeff1 = 3.1
coeff2 = 3.5

#function to get preds
normalmethod_2 <- function(tempdf){
  normpred <- rep(NA,nrow(tempdf))
  
  #go through every row
  for(i in 1:nrow(tempdf)){
    #not attack on default
    flag = FALSE
    #go through every column
    for(j in 1:ncol(tempdf)){
      #if > 1sd from mean then flag trigger flag
      # check1 = tempdf[i,j] - doublerange[1,j]
      # if(doublerange[2,j] >0){
      #   check11 = (tempdf[i,j] - doublerange[1,j])/doublerange[2,j]
      # }
      # else{check11 = 1}
      # check2 = doublerange[3,j]-tempdf[i,j]
      # if(doublerange[4,j] >0){
      #   check22 = (doublerange[3,j]-tempdf[i,j])/doublerange[4,j]
      # }
      # else{check22 = 1}
      # if(check1 >=0 && check11 <= 0.01){
      #   flag = TRUE
      # }
      # else if(check2 >=0 && check22 <= 0.01){
      #   flag = TRUE
      # } 
      if(tempdf[i,j] - doublerange[1,j] > coeff1*doublerange[2,j] || doublerange[3,j] - tempdf[i,j] > coeff2*doublerange[4,j]){
        flag = TRUE
      }
    }
    normpred[i]=flag
    
  }
  return(normpred)
}


normpred_2 <- normalmethod_2(tempdf)

# print("Dataset2")
# NDM <- table(normpred_2, dataset2$ATT_FLAG)
NDM <- table(normpred_2, spedpred$ATT_FLAG)
NDM
F1calc(NDM[4],NDM[2],NDM[3])
```

```{r}

```
