---
title: "AE Competition"
output: html_notebook
---

Read in datasets
```{r}
setwd("D:/School Stuff/40 .220 The Analytics Edge/Competition/Code")
dataset1 <- read.csv("../Data/train_dataset01.csv")
dataset2 <- read.csv("../Data/train_dataset02.csv")
dataset3 <- read.csv("../Data/test_dataset.csv")
sample <- read.csv("../Data/sample_submission.csv")

```

F1 Calculator based on TP, FP and FN
```{r}
F1calc <- function(TP,FP,FN){
  p = TP/ (TP+FP)
  r = TP/ (TP+FN)
  return((2*p*r)/(p+r))
}

```


```{r}
str(dataset1)
str(dataset2)

```
Naive Bayes

```{r}
NB <- table(dataset2$ATT_FLAG)
NB
message("F1 Score:")
F1calc(NB[2],NB[1],0)
```

Full dataset glm (all var)

```{r}
library(caTools)
set.seed(1)
fullglmsplit <- sample.split(dataset2$ATT_FLAG, SplitRatio = 0.7)
fullglmtrain <- subset(dataset2, fullglmsplit == TRUE)
fullglmtest <- subset(dataset2, fullglmsplit == FALSE)
```

```{r}
fullglm <- glm(data=fullglmtrain, family="binomial", 
               as.factor(ATT_FLAG)~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)

#On training
fullglmPredict <- predict(fullglm, newdata = fullglmtrain, type="response")
FDGA <- table(fullglmPredict > 0.5, fullglmtrain$ATT_FLAG)

print("On Training Dataset")
FDGA
F1calc(FDGA[4],FDGA[2],FDGA[3])

#ON test
fullglmPredict <- predict(fullglm, newdata = fullglmtest, type="response")
FDGA <- table(fullglmPredict > 0.5, fullglmtest$ATT_FLAG)

print("On Test Dataset")
FDGA
F1calc(FDGA[4],FDGA[2],FDGA[3])

#ON all dataset 2
fullglmPredict <- predict(fullglm, newdata = dataset2, type="response")
FDGA <- table(fullglmPredict > 0.5, dataset2$ATT_FLAG)

print("On ALL of dataset 2")
FDGA
F1calc(FDGA[4],FDGA[2],FDGA[3])

#ON all dataset 1 (should get none)
fullglmPredict <- predict(fullglm, newdata = dataset1, type="response")
FDGA <- table(fullglmPredict > 0.5, dataset1$ATT_FLAG)

print("On dataset 1")
FDGA
```

Full dataset glm (best vars)
```{r}
selectglm <- glm(data=fullglmtrain, family="binomial", 
               as.factor(ATT_FLAG)~LEVEL_T1+LEVEL_T4+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J269+PRESSURE_J415+PRESSURE_J317+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU4+FLOW_PU6+FLOW_PU7+FLOW_PU10+FLOW_PU11+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11)
summary(selectglm)

#On training
selectglmPredict <- predict(selectglm, newdata = fullglmtrain, type="response")
FDGS <- table(selectglmPredict > 0.5, fullglmtrain$ATT_FLAG)

print("On Training Dataset")
FDGS
F1calc(FDGS[4],FDGS[2],FDGS[3])

#ON test
selectglmPredict <- predict(selectglm, newdata = fullglmtest, type="response")
FDGS <- table(selectglmPredict > 0.5, fullglmtest$ATT_FLAG)

print("On Test Dataset")
FDGS
F1calc(FDGS[4],FDGS[2],FDGS[3])

#ON all dataset 2
selectglmPredict <- predict(selectglm, newdata = dataset2, type="response")
FDGS <- table(selectglmPredict > 0.5, dataset2$ATT_FLAG)

print("On ALL of dataset 2")
FDGS
F1calc(FDGS[4],FDGS[2],FDGS[3])

#ON all dataset 1 (should get none)
selectglmPredict <- predict(selectglm, newdata = dataset1, type="response")
FDGS <- table(selectglmPredict > 0.5, dataset1$ATT_FLAG)

print("On dataset 1")
FDGS
```


Randforest
```{r}
library(randomForest)
set.seed(2e4)
forest_fulldata <- randomForest(data = fullglmtrain, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)

pred.forest_fulldata <- predict(forest_fulldata, newdata = fullglmtrain)
FDRF <- table(pred.forest_fulldata, fullglmtrain$ATT_FLAG)

print("On Training Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = fullglmtest)
FDRF <- table(pred.forest_fulldata, fullglmtest$ATT_FLAG)

print("On Test Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = dataset2)
FDRF <- table(pred.forest_fulldata, dataset2$ATT_FLAG)

pred.forest_fulldata <- predict(forest_fulldata, newdata = dataset1)
FDRF <- table(pred.forest_fulldata, dataset1$ATT_FLAG)

print("On Dataset 1")
FDRF
```
Checking RF
```{r}
vu <- varUsed(forest_fulldata, count= TRUE)                      #freq of variables used in the random forest
vusorted <- sort(vu, decreasing = FALSE, index.return = TRUE) #sorts the fq
dotchart(vusorted$x, names(forest_fulldata$forest$xlevels[vusorted$ix])) #draws a cleveland dot plot

varImpPlot(forest_fulldata) #looking at impurity metric > want to find average reduction in impurity
importance(forest_fulldata) #see which variables are the most impt (higher = more impt)
```

 on dataset3
```{r}
pred.forest_fulldata <- predict(forest_fulldata, newdata = dataset3)
table(pred.forest_fulldata)
```

Writing to CSV
```{r}
out=data.frame(DATETIME=dataset3$DATETIME,ATT_FLAG=pred.forest_fulldata)
str(out)
write.csv(out,file="test.csv",row.names=FALSE)
```


Justinian Selected
```{r}
library(randomForest)
set.seed(2e4)
forest_fulldata <- randomForest(data = fullglmtrain, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T7+
                 FLOW_PU1+FLOW_PU2+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU10+FLOW_PU11+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11)

pred.forest_fulldata <- predict(forest_fulldata, newdata = fullglmtrain)
```

testing to add time
```{r}
library(caTools)
set.seed(1)
fullglmsplit <- sample.split(dataset2$ATT_FLAG, SplitRatio = 0.5)
fullglmtrain <- subset(dataset2, fullglmsplit == TRUE)
fullglmtest <- subset(dataset2, fullglmsplit == FALSE)

testtrain <- fullglmtrain
testtrain$id =seq.int(nrow(testtrain))

set.seed(2e4)
forest_test <- randomForest(data = testtrain, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)


testmodel(forest_test)
```

```{r}
testmodel <- function(model){
  pred <- predict(model, newdata = fullglmtrain)
  FDRF <- table(pred, fullglmtrain$ATT_FLAG)
  
  print("On Training Dataset")
  print(FDRF)
  print(F1calc(FDRF[4],FDRF[2],FDRF[3]))
  
  pred <- predict(model, newdata = fullglmtest)
  FDRF <- table(pred, fullglmtest$ATT_FLAG)
  
  print("On Test Dataset")
  print(FDRF)
  print(F1calc(FDRF[4],FDRF[2],FDRF[3]))
  
  pred <- predict(model, newdata = dataset2)
  FDRF <- table(pred, dataset2$ATT_FLAG)
  
  print("On Full Dataset")
  print(FDRF)
  print(F1calc(FDRF[4],FDRF[2],FDRF[3]))
  
  
  pred <- predict(model, newdata = dataset1)
  FDRF <- table(pred, dataset1$ATT_FLAG)
  
  print("On Dataset 1")
  FDRF
}
```


split dataset manually 13550
```{r}
df1 <- dataset2[6602:6700,]
df1 <- rbind(df1,dataset2[7710:7750,])
df1 <- rbind(df1,dataset2[8898:9000,])
df1 <- rbind(df1,dataset2[10866:11000,])
df1 <- rbind(df1,dataset2[13550:13650,])
df1 <- rbind(df1,dataset2[14482:14650,])
df1 <- rbind(df1,dataset2[15242:15444,])

library(dplyr)
df2 <-anti_join(dataset2, df1)

df1 <- rbind(df1,dataset1[10000:ncol(dataset1),])

library(randomForest)
set.seed(2e4)
forest_fulldata <- randomForest(data = df1, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)

pred.forest_fulldata <- predict(forest_fulldata, newdata = df1)
FDRF <- table(pred.forest_fulldata, df1$ATT_FLAG)

print("On Training Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

pred.forest_fulldata <- predict(forest_fulldata, newdata = df2)
FDRF <- table(pred.forest_fulldata, df2$ATT_FLAG)

print("On Test Dataset")
FDRF
F1calc(FDRF[4],FDRF[2],FDRF[3])

-pred.forest_fulldata <- predict(forest_fulldata, newdata = dataset1)
FDRF <- table(pred.forest_fulldata, dataset1$ATT_FLAG)

print("On Dataset 1")
FDRF

```



##########
Marking method
```{r}
# Creating huge dataset called mark code which combines all 3 datasets
markcode = dataset3
markcode$ATT_FLAG = as.logical(read.csv("Team17_Try6b.csv")$ATT_FLAG)
tempdf <- dataset2
tempdf$ATT_FLAG <- as.logical(tempdf$ATT_FLAG)
markcode <- rbind(markcode,tempdf)
tempdf <- dataset1
tempdf$ATT_FLAG <- as.logical(tempdf$ATT_FLAG)
markcode <- rbind(markcode,tempdf)
markcode$ATT_FLAG = as.factor(markcode$ATT_FLAG)

#throw into RF model
```

```{r}
library(randomForest)
set.seed(2e4)
RF_Mark <- randomForest(data = markcode, ATT_FLAG~LEVEL_T1+LEVEL_T2+LEVEL_T3+LEVEL_T4+LEVEL_T5+LEVEL_T6+LEVEL_T7+
                 PRESSURE_J280+PRESSURE_J269+PRESSURE_J300+PRESSURE_J256+PRESSURE_J289+PRESSURE_J415+PRESSURE_J302+PRESSURE_J306+PRESSURE_J307+PRESSURE_J317+PRESSURE_J14+PRESSURE_J422+
                 FLOW_PU1+FLOW_PU2+FLOW_PU3+FLOW_PU4+FLOW_PU5+FLOW_PU6+FLOW_PU7+FLOW_PU8+FLOW_PU9+FLOW_PU10+FLOW_PU11+FLOW_V2+
                 STATUS_PU1+STATUS_PU2+STATUS_PU4+STATUS_PU6+STATUS_PU7+STATUS_PU10+STATUS_PU11+STATUS_V2)

pred.RF_Mark <- predict(RF_Mark, newdata = dataset1)
RFM <- table(pred.RF_Mark, dataset1$ATT_FLAG)
print("On Dataset1")
RFM

pred.RF_Mark <- predict(RF_Mark, newdata = dataset2)
RFM <- table(pred.RF_Mark, dataset2$ATT_FLAG)
print("On Dataset2")
RFM
F1calc(RFM[4],RFM[2],RFM[3])

pred.RF_Mark <- predict(RF_Mark, newdata = dataset3)
RFM <- table(pred.RF_Mark, read.csv("Team17_Try6b.csv")$ATT_FLAG)
print("On Dataset3")
RFM
F1calc(RFM[4],RFM[2],RFM[3])
```

```{r}

```

```{r}

```